// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace api.Models;

public partial class ArmsTable
{
    public int ArmsId { get; set; }

    public string Arm { get; set; }

    public string SchoolId { get; set; }

    public virtual SchoolAdminRegistration School { get; set; }
}