// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace api.Models;

public partial class Attendance
{
    public string DaysDate { get; set; }

    public string StudentRollNumber { get; set; }

    public string Status { get; set; }

    public string Class { get; set; }

    public int ArmsId { get; set; }

    public string Day { get; set; }

    public string SchoolId { get; set; }

    public virtual StudentRegTab StudentRollNumberNavigation { get; set; }
}