// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace api.Models;

public partial class Authenticate
{
    public string EmailAdress { get; set; }

    public string PassWord { get; set; }

    public int? Role { get; set; }
}