// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace api.Models;

public partial class ClassesTable
{
    [Key]
    public int ClassId { get; set; }

    public string SchoolId { get; set; }

    public string Class { get; set; }

    public virtual SchoolAdminRegistration School { get; set; }
}