// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace api.Models;

public partial class CountryTable
{
    public int CountryId { get; set; }

    public string Countrys { get; set; }

    public virtual ICollection<State> States { get; set; } = new List<State>();
}