// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace api.Models;

public partial class GradesTable
{
    public int GradesId { get; set; }

    public string SchoolId { get; set; }

    public int LowerLimit { get; set; }

    public int UpperLimit { get; set; }

    public string Grades { get; set; }

    public string Remark { get; set; }

    public virtual SchoolAdminRegistration School { get; set; }
}