// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace api.Models;

public partial class Lga
{
    public int Lgaid { get; set; }

    public string Lga1 { get; set; }

    public int StateId { get; set; }

    public virtual State State { get; set; }
}