// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace api.Models;

public partial class PaymentTable
{
    public int PaymentId { get; set; }

    public string Name { get; set; }

    public string SchoolId { get; set; }

    public string StudentRollnum { get; set; }

    public DateTime PaymentDate { get; set; }

    public string StudentClass { get; set; }

    public decimal Fees { get; set; }

    public decimal AmountPaid { get; set; }

    public string Term { get; set; }

    public string Status { get; set; }

    public virtual SchoolAdminRegistration School { get; set; }

    public virtual StudentRegTab StudentRollnumNavigation { get; set; }
}