// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace api.Models;

public partial class ResultTable
{
    public string StudentRollNumber { get; set; }

    public int SubjectId { get; set; }

    public decimal CatTotal { get; set; }

    public decimal ExamsTotal { get; set; }

    public decimal SumTotal { get; set; }

    public int ResultId { get; set; }

    public virtual StudentRegTab StudentRollNumberNavigation { get; set; }
}