// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace api.Models;

public partial class SchoolAdminRegistration
{
    public int Id { get; set; }

    public Guid? UserId { get; set; }

    public string SchoolId { get; set; }

    public string SchoolName { get; set; }

    public string AdminOtherNames { get; set; }

    public string AdminSurName { get; set; }

    public string StreetName { get; set; }

    public int LgaId { get; set; }

    public DateTimeOffset? RegistrationDate { get; set; }

    public string SchoolPhoneNumber { get; set; }

    public string SchoolEmailAdress { get; set; }

    public string SchoolPostalCode { get; set; }

    public string Gender { get; set; }

    public byte[] ProfilePixs { get; set; }

    public DateTimeOffset? LastEditedOn { get; set; }

    public virtual ICollection<ArmsTable> ArmsTables { get; set; } = new List<ArmsTable>();

    public virtual ICollection<ClassesTable> ClassesTables { get; set; } = new List<ClassesTable>();

    public virtual ICollection<ExamsTable> ExamsTables { get; set; } = new List<ExamsTable>();

    public virtual ICollection<FeesTable> FeesTables { get; set; } = new List<FeesTable>();

    public virtual ICollection<GradesTable> GradesTables { get; set; } = new List<GradesTable>();

    public virtual ICollection<PaymentTable> PaymentTables { get; set; } = new List<PaymentTable>();

    public virtual ICollection<StudentRegTab> StudentRegTabs { get; set; } = new List<StudentRegTab>();

    public virtual ICollection<TeacherTab> TeacherTabs { get; set; } = new List<TeacherTab>();

    public virtual ICollection<TestTable> TestTables { get; set; } = new List<TestTable>();
}