// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace api.Models;

public partial class State
{
    public int StateId { get; set; }

    public string state { get; set; }

    public int CountryId { get; set; }

    public virtual CountryTable Country { get; set; }

    public virtual ICollection<Lga> Lgas { get; set; } = new List<Lga>();
}