// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace api.Models;

public partial class Subjectteacher
{
    public int Id { get; set; }

    public int SubjectId { get; set; }

    public string TeacherName { get; set; }

    public string TeacherId { get; set; }

    public string Class { get; set; }

    public string SchoolId { get; set; }

    public virtual SubjectTable Subject { get; set; }
}