// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace api.Models;

public partial class SubjectTable
{
    public int SubjectId { get; set; }

    public string SchoolId { get; set; }

    public string SubjectName { get; set; }

    public virtual ICollection<Subjectteacher> Subjectteachers { get; set; } = new List<Subjectteacher>();
}