// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace api.Models;

public partial class TeacherTab
{
    public int RollId { get; set; }

    public Guid UserId { get; set; }

    public string TeacherRollId { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public string IsClassTeacher { get; set; }

    public string PhoneNumber { get; set; }

    public string ResidentialAdress { get; set; }

    public DateTime Dob { get; set; }

    public int LocalGovernment { get; set; }

    public string EmailAdress { get; set; }

    public int SubjectId { get; set; }

    public byte[] Passport { get; set; }

    public string SchoolId { get; set; }

    public string Password { get; set; }

    public string PasswordQuestion { get; set; }

    public string PasswordAnswer { get; set; }

    public DateTime? RegistrationDate { get; set; }

    public DateTime? LastEditedOn { get; set; }

    public string Gender { get; set; }

    public virtual SchoolAdminRegistration School { get; set; }
}