// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace api.Models;

public partial class TeachersAttaindance
{
    public string TeacherId { get; set; }

    public string Status { get; set; }

    public DateOnly Date { get; set; }

    public string Day { get; set; }
}