// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace api.Models;

public partial class TermTable
{
    public int TermId { get; set; }

    public string Term { get; set; }
}