// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace api.Models;

public partial class TestTable
{
    public int TestId { get; set; }

    public string StudentRollNum { get; set; }

    public string SublectName { get; set; }

    public string TestType { get; set; }

    public DateOnly Date { get; set; }

    public decimal Scores { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Term { get; set; }

    public string SchoolId { get; set; }

    public string FillersId { get; set; }

    public virtual SchoolAdminRegistration School { get; set; }

    public virtual StudentRegTab StudentRollNumNavigation { get; set; }
}