// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace api.Models;

public partial class TestType
{
    public string SchoolID {get; set;}
    public string TesyType { get; set; }
}