// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace api.Models;

public partial class UploadTable
{
    public int UploadId { get; set; }

    public string SchoolId { get; set; }

    public string Class { get; set; }

    public int SubjectId { get; set; }

    public DateOnly UploadDate { get; set; }

    public string FileType { get; set; }

    public byte[] FileData { get; set; }

    public string Filename { get; set; }

    public string Description { get; set; }

    public string OriginalName { get; set; }
}